apiVersion: v1
kind: Service
metadata:
  name: hello-world-svc
  labels:
    app: hello-world-app
spec:
  selector:
    app: hello-world-app
  ports:
    - name: http
      protocol: TCP
      port: 32777
      targetPort: 32777